# DevMinds.ai Provider Configuration Template

providers:
  deepseek:
    name: DeepSeek
    apiType: openai
    baseUrl: https://api.deepseek.com/v1
    apiKeyEnvVar: DEEPSEEK_API_KEY
    models:
      - deepseek-chat
      - deepseek-reasoner
  anthropic:
    name: Anthropic
    apiType: anthropic
    baseUrl: https://api.anthropic.com
    apiKeyEnvVar: ANTHROPIC_AUTH_TOKEN
    models:
      - claude-3-5-haiku-20241022
      - claude-3-5-sonnet-20240620
      - claude-3-5-sonnet-20241022
      - claude-3-7-sonnet-20250219
      - claude-3-haiku-20240307
      - claude-3-opus-20240229
      - claude-3-sonnet-20240229
      - claude-opus-4-1-20250805
      - claude-opus-4-20250514
      - claude-sonnet-4-20250514
  openai:
    name: OpenAI
    apiType: openai
    baseUrl: https://api.openai.com/v1
    apiKeyEnvVar: OPENAI_API_KEY
    models:
      - codex-mini-latest
      - gpt-4-turbo
      - gpt-4.1
      - gpt-4.1-mini
      - gpt-4.1-nano
      - gpt-4o
      - gpt-4o-mini
      - gpt-5
      - gpt-5-mini
      - gpt-5-nano
      - o1
      - o1-pro
      - o3
      - o3-deep-research
      - o3-mini
      - o3-pro
      - o4-mini
      - o4-mini-deep-research
  zhipuai:
    name: Zhipu AI
    apiType: anthropic
    baseUrl: https://open.bigmodel.cn/api/anthropic
    apiKeyEnvVar: ZHIPUAI_API_KEY
    models:
      - glm-4.5
      - glm-4.5-air
      - glm-4.5-flash
      - glm-4.5v
  zai:
    name: Z.AI
    apiType: openai
    baseUrl: https://api.z.ai/api/paas/v4/
    apiKeyEnvVar: ZAI_API_KEY
    models:
      - glm-4.5
      - glm-4.5-air
      - glm-4.5-flash
      - glm-4.5v
